version: '3.8'

services:
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
      volumes:
        - ./database:/var/lib/postgresql/data

    redis:
      image: redis
      volumes:
        - ./redis-database:/data
      
    back_end:
      image: backend
      ports:
      - 8080:8080
      environment:
        REDIS_HOST: redis
        POSTGRES_HOST: db

    front_end:
      image: frontend
      ports:
      - 5000:5000
      
