version: '3.8'

services:
    back_end:
      image: backend
      ports:
      - 8080:8080

    front_end:
      image: frontend
      ports:
      - 5000:5000

The images backend and frontend were already built in part 1, so it works with those.
