FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN apt update && apt install -y curl &&\

    curl -sL https://deb.nodesource.com/setup_16.x | bash &&\

    apt install -y nodejs &&\
    
    npm install &&\

    npm run build &&\

    npm install -g serve &&\
    
    apt-get purge -y --auto-remove curl &&\
    
    rm -rf /var/lib/apt/lists/* &&\

    useradd -m testuser &&\
    
    chown testuser /usr/src/app

USER testuser

CMD ["serve", "-s", "-l", "5000", "build"]
