FROM golang

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build
RUN useradd -m testuser
RUN chown testuser /usr/src/app

USER testuser

CMD "./server"
