version: '3.8'

services:

    redis:
      image: redis
      
    back_end:
      image: backend
      ports:
      - 8080:8080
      environment:
        REDIS_HOST: redis

    front_end:
      image: frontend
      ports:
      - 5000:5000

Same images used as in last exercise.
