version: "3.8"

services:
  ml_frontend:
    image: ml_frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    
  ml_backend:
    image: ml_backend
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - ml_training
    
  ml_training:
    image: ml_training
    build: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/src/data

volumes:
  model:
  images:
  data:
