FROM node:16-alpine3.14
EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install &&\

    npm run build &&\

    npm install -g serve &&\
    
    adduser -D testuser &&\
    
    chown testuser /usr/src/app

USER testuser

CMD ["serve", "-s", "-l", "5000", "build"]
